name: Run Stocks Script

on:
  schedule:
    - cron: '0 10 * * *' # This schedules the job to run every day at 10 AM UTC
  workflow_dispatch:

jobs:
  run-stocks-script:
    runs-on: ubuntu-latest # Using an Ubuntu runner
    
    steps:
      # Check out the repository
      - name: Checkout code
        uses: actions/checkout@v3
        
      # Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x' # You can specify a specific Python version, like '3.9'

      # Install dependencies (if any)
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt # Assuming you have a requirements.txt file

      # Run the Python script
      - name: Run stocks.py
        run: |
          python stocks.py