name: Run Python Script and Push Changes

on:
  schedule:
    - cron: '0 10 * * *'  # Run at 10:00 AM UTC every day
  workflow_dispatch:  # Allow manual trigger (optional)

jobs:
  run-stocks-script:
    runs-on: ubuntu-latest  # You can change this to another OS like 'windows-latest' or 'macos-latest'

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3  # Clones the repository

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'  # Use the Python version you need (e.g., 3.10)

    - name: Install dependencies
      run: pip install -r requirements.txt  # Install dependencies from requirements.txt

    - name: Run stocks.py script
      run: python stocks.py  # Run the Python script

    - name: Commit and push changes
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add .
        git commit -m "Automated update from GitHub Actions" || echo "No changes to commit"
        git push origin main  # Change 'main' to the correct branch if needed